vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    images:
      uri_prefix: api/images
      upload_destination: '%kernel.project_dir%/public/api/images'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
#      directory_namer:
#        service: App\Namer\ImageDirectoryNamer
      inject_on_load: true
